## Imports and configuration

In [45]:
import json
import pandas as pd
from pathlib import Path

BASE_DIR = Path(".")

FILES = {
    "short_retrieval": BASE_DIR / "retrieval_improvement_outputs" / "short_queries_117_reranked_outputs.json",
    "long_retrieval": BASE_DIR / "retrieval_improvement_outputs" / "long_queries_41_reranked_outputs.json",
    "short_eval": BASE_DIR / "failure_analysis_results" / "short_queries_117_retrieval_outputs.json",
    "long_eval": BASE_DIR / "failure_analysis_results" / "long_queries_41_retrieval_outputs.json",
}

for name, path in FILES.items():
    print(f"{name}: {'FOUND' if path.exists() else 'MISSING'}")

short_retrieval: FOUND
long_retrieval: FOUND
short_eval: FOUND
long_eval: FOUND

Load the four files

In [46]:
def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

short_retrieval = load_json(FILES["short_retrieval"])
long_retrieval = load_json(FILES["long_retrieval"])
short_eval = load_json(FILES["short_eval"])
long_eval = load_json(FILES["long_eval"])

print("Short retrieval:", len(short_retrieval))
print("Long retrieval:", len(long_retrieval))
print("Short evaluation:", short_eval["total_queries"])
print("Long evaluation:", long_eval["total_queries"])

Short retrieval: 117
Long retrieval: 41

TypeError: list indices must be integers or slices, not str

Normalize evaluation data

In [38]:
def normalize_evaluation(data):
    rows = []

    for i, item in enumerate(data["results"]):
        rows.append({
            "query_id": i + 1,
            "query": item.get("query", ""),
            "expected_document": item.get("expected", ""),
            "retrieved": item.get("retrieved", []),
            "top_1": item.get("top_1", False),
            "top_3": item.get("top_3", False),
            "top_5": item.get("top_5", False),
        })

    return pd.DataFrame(rows)


short_df = normalize_evaluation(short_eval)
long_df = normalize_evaluation(long_eval)

print(short_df.shape)
print(long_df.shape)

display(short_df.head())

(117, 7)
(41, 7)

,query_id,query,expected_document,retrieved,top_1,top_3,top_5
0,1,How much vacation time do employees get?,Vacation and Sick Leave.md,"[Vacation and Sick Leave.md, Sabbatical.md, Ne...",True,True,True
1,2,Can I take leave after having a baby?,New Parent Leave.md,"[New Parent Leave.md, Other Protected Absences...",True,True,True
2,3,What holidays does the company observe?,Holiday List.md,"[Holiday List.md, README.md, Communication and...",True,True,True
3,4,How many days of PTO do I earn per month?,Vacation and Sick Leave.md,"[Vacation and Sick Leave.md, Other Protected A...",True,True,True
4,5,"I'm not feeling well today, how does sick leav...",Vacation and Sick Leave.md,"[README.md, Vacation and Sick Leave.md, Other ...",False,True,True

Remove README from evaluation results

In [39]:
def remove_readme(results):
    return [
        doc for doc in results
        if doc != "README.md"
    ]


short_df["retrieved_no_readme"] = short_df["retrieved"].apply(remove_readme)
long_df["retrieved_no_readme"] = long_df["retrieved"].apply(remove_readme)

print("README removed from evaluation rankings.")

README removed from evaluation rankings.

Calculate the improved rank

In [40]:
def get_rank(expected, retrieved):
    for rank, doc in enumerate(retrieved, start=1):
        if doc == expected:
            return rank
    return None


short_df["improved_rank"] = short_df.apply(
    lambda row: get_rank(
        row["expected_document"],
        row["retrieved_no_readme"]
    ),
    axis=1
)

long_df["improved_rank"] = long_df.apply(
    lambda row: get_rank(
        row["expected_document"],
        row["retrieved_no_readme"]
    ),
    axis=1
)

print("Short remaining Top-1 failures:",
      (short_df["improved_rank"] != 1).sum())

print("Long remaining Top-1 failures:",
      (long_df["improved_rank"] != 1).sum())

Short remaining Top-1 failures: 26
Long remaining Top-1 failures: 5

Extract only remaining failures

In [41]:
short_failures = short_df[
    short_df["improved_rank"] != 1
].copy()

long_failures = long_df[
    long_df["improved_rank"] != 1
].copy()

print("SHORT FAILURES:", len(short_failures))
print("LONG FAILURES:", len(long_failures))

SHORT FAILURES: 26
LONG FAILURES: 5

Inspect all remaining failures

In [42]:
def display_failures(df, title):
    print("=" * 100)
    print(title)
    print("=" * 100)

    for _, row in df.iterrows():

        print(f"\nQuery ID: {row['query_id']}")
        print(f"Query: {row['query']}")
        print(f"Expected: {row['expected_document']}")
        print(f"Improved Rank: {row['improved_rank']}")

        print("\nRetrieved:")
        for rank, doc in enumerate(row["retrieved_no_readme"], 1):
            marker = " <-- EXPECTED" if doc == row["expected_document"] else ""
            print(f"  {rank}. {doc}{marker}")

        print("-" * 100)


display_failures(short_failures, "SHORT QUERY REMAINING FAILURES")
display_failures(long_failures, "LONG QUERY REMAINING FAILURES")

====================================================================================================
SHORT QUERY REMAINING FAILURES
====================================================================================================

Query ID: 6
Query: Is Thanksgiving a day off at Clef?
Expected: Holiday List.md
Improved Rank: nan

Retrieved:
  1. Vacation and Sick Leave.md
  2. Other Protected Absences.md
  3. Drug and Alcohol Policy.md
  4. Welcome to Clef.md
  5. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 10
Query: I need some time away, what are my options?
Expected: Vacation and Sick Leave.md
Improved Rank: nan

Retrieved:
  1. Communication and Transparency.md
  2. Working Remotely.md
  3. Other Protected Absences.md
  4. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 15
Query: I've been here 5 years, what's the deal with the long break?
Expected: Sabbatical.md
Improved Rank: 2.0

Retrieved:
  1. Vacation and Sick Leave.md
  2. Sabbatical.md <-- EXPECTED
  3. Welcome to Clef.md
  4. Other Protected Absences.md
----------------------------------------------------------------------------------------------------

Query ID: 18
Query: Does Clef pay for online courses and books?
Expected: Continuing Education.md
Improved Rank: 2.0

Retrieved:
  1. Working Remotely.md
  2. Continuing Education.md <-- EXPECTED
  3. Other Protected Absences.md
  4. Continuing Education.md <-- EXPECTED
  5. Welcome to Clef.md
----------------------------------------------------------------------------------------------------

Query ID: 36
Query: How much do the founders make?
Expected: Salary and Equity Compensation.md
Improved Rank: 3.0

Retrieved:
  1. Budgeting.md
  2. Complaint Policy.md
  3. Salary and Equity Compensation.md <-- EXPECTED
  4. Salary and Equity Compensation.md <-- EXPECTED
  5. Objectives and Key Results.md
----------------------------------------------------------------------------------------------------

Query ID: 46
Query: I have a family emergency, what should I do?
Expected: Other Protected Absences.md
Improved Rank: 2.0

Retrieved:
  1. Working Remotely.md
  2. Other Protected Absences.md <-- EXPECTED
  3. Working Remotely.md
  4. Communication and Transparency.md
  5. Communication and Transparency.md
----------------------------------------------------------------------------------------------------

Query ID: 70
Query: Can we have beer at a company celebration?
Expected: Drug and Alcohol Policy.md
Improved Rank: 2.0

Retrieved:
  1. Welcome to Clef.md
  2. Drug and Alcohol Policy.md <-- EXPECTED
  3. Working Remotely.md
  4. Continuing Education.md
  5. Policy Changes.md
----------------------------------------------------------------------------------------------------

Query ID: 71
Query: Can Clef fire me without a reason?
Expected: At-Will Employment.md
Improved Rank: nan

Retrieved:
  1. Complaint Policy.md
  2. Employee Privacy.md
  3. Employee Privacy.md
  4. Other Protected Absences.md
  5. Employee Privacy.md
----------------------------------------------------------------------------------------------------

Query ID: 76
Query: What are Clef's core values?
Expected: Clef Values.md
Improved Rank: nan

Retrieved:
  1. Welcome to Clef.md
  2. Continuing Education.md
  3. Equal Opportunity Employment.md
----------------------------------------------------------------------------------------------------

Query ID: 78
Query: How does Clef think about inclusion?
Expected: Clef Values.md
Improved Rank: nan

Retrieved:
  1. Equal Opportunity Employment.md
  2. Welcome to Clef.md
  3. Welcome to Clef.md
  4. Welcome to Clef.md
----------------------------------------------------------------------------------------------------

Query ID: 79
Query: Why does Clef emphasize trust?
Expected: Clef Values.md
Improved Rank: nan

Retrieved:
  1. Welcome to Clef.md
  2. One on Ones.md
  3. Employee Privacy.md
----------------------------------------------------------------------------------------------------

Query ID: 80
Query: What is Clef's mission?
Expected: Mission Statement.md
Improved Rank: nan

Retrieved:
  1. Welcome to Clef.md
  2. Welcome to Clef.md
  3. Handbook Introduction.md
----------------------------------------------------------------------------------------------------

Query ID: 81
Query: What problem is Clef trying to solve?
Expected: Mission Statement.md
Improved Rank: nan

Retrieved:
  1. Complaint Policy.md
  2. Product Manifesto.md
  3. Welcome to Clef.md
  4. Welcome to Clef.md
----------------------------------------------------------------------------------------------------

Query ID: 84
Query: How does Clef celebrate a new employee's first day?
Expected: Welcome to Clef.md
Improved Rank: 2.0

Retrieved:
  1. Referral Bonuses.md
  2. Welcome to Clef.md <-- EXPECTED
  3. Welcome to Clef.md <-- EXPECTED
  4. Policy Changes.md
  5. Continuing Education.md
----------------------------------------------------------------------------------------------------

Query ID: 85
Query: I just got hired, where do I start?
Expected: Welcome to Clef.md
Improved Rank: 2.0

Retrieved:
  1. Referral Bonuses.md
  2. Welcome to Clef.md <-- EXPECTED
  3. Working Remotely.md
  4. Budgeting.md
----------------------------------------------------------------------------------------------------

Query ID: 87
Query: Who is the CEO of Clef?
Expected: Handbook Introduction.md
Improved Rank: 3.0

Retrieved:
  1. Welcome to Clef.md
  2. Welcome to Clef.md
  3. Handbook Introduction.md <-- EXPECTED
----------------------------------------------------------------------------------------------------

Query ID: 96
Query: What happens on Fridays in terms of team updates?
Expected: Communication and Transparency.md
Improved Rank: 2.0

Retrieved:
  1. Policy Changes.md
  2. Communication and Transparency.md <-- EXPECTED
  3. Communication and Transparency.md <-- EXPECTED
  4. Policy Changes.md
  5. Communication and Transparency.md <-- EXPECTED
----------------------------------------------------------------------------------------------------

Query ID: 99
Query: Who do employees report to at Clef?
Expected: Direct Reports.md
Improved Rank: 2.0

Retrieved:
  1. Complaint Policy.md
  2. Direct Reports.md <-- EXPECTED
  3. Employee Privacy.md
  4. Other Protected Absences.md
----------------------------------------------------------------------------------------------------

Query ID: 100
Query: What is Clef's core product value?
Expected: Product Manifesto.md
Improved Rank: nan

Retrieved:
  1. Welcome to Clef.md
  2. Welcome to Clef.md
  3. Equal Opportunity Employment.md
----------------------------------------------------------------------------------------------------

Query ID: 102
Query: How is company spending organized at Clef?
Expected: Budgeting.md
Improved Rank: nan

Retrieved:
  1. Continuing Education.md
  2. Continuing Education.md
  3. Welcome to Clef.md
  4. Welcome to Clef.md
  5. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 103
Query: What are the budget categories at Clef?
Expected: Budgeting.md
Improved Rank: nan

Retrieved:
  1. Continuing Education.md
  2. Continuing Education.md
  3. Sharing Files.md
  4. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 108
Query: What are the meeting time requirements at Clef?
Expected: Effective Meetings.md
Improved Rank: nan

Retrieved:
  1. Welcome to Clef.md
  2. One on Ones.md
  3. Continuing Education.md
  4. Welcome to Clef.md
  5. Vacation and Sick Leave.md
----------------------------------------------------------------------------------------------------

Query ID: 111
Query: What tools does Clef use for policy discussions?
Expected: Policy Changes.md
Improved Rank: nan

Retrieved:
  1. Working Remotely.md
  2. Welcome to Clef.md
----------------------------------------------------------------------------------------------------

Query ID: 112
Query: Why did Clef open source their employee handbook?
Expected: README.md
Improved Rank: nan

Retrieved:
  1. Handbook Introduction.md
  2. Policy Changes.md
  3. Sharing Files.md
  4. Employee Privacy.md
  5. Complaint Policy.md
----------------------------------------------------------------------------------------------------

Query ID: 116
Query: If something bad happens at work who should I talk to — my manager or HR?
Expected: Complaint Policy.md
Improved Rank: nan

Retrieved:
  1. One on Ones.md
  2. One on Ones.md
  3. Effective Meetings.md
  4. Working Remotely.md
  5. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 117
Query: Does the code of conduct apply inside the office or only online?
Expected: Code of Conduct in the Community.md
Improved Rank: 2.0

Retrieved:
  1. Employee Privacy.md
  2. Code of Conduct in the Community.md <-- EXPECTED
  3. Employee Privacy.md
  4. Working Remotely.md
----------------------------------------------------------------------------------------------------
====================================================================================================
LONG QUERY REMAINING FAILURES
====================================================================================================

Query ID: 2
Query: My spouse and I are expecting a baby in a few months and I want to understand the full maternity and paternity leave policy including how it interacts with California state disability programs
Expected: New Parent Leave.md
Improved Rank: 2.0

Retrieved:
  1. Other Protected Absences.md
  2. New Parent Leave.md <-- EXPECTED
  3. Healthcare and Disability Insurance.md
  4. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 4
Query: I have a chronic illness that sometimes makes it hard to come into the office regularly — is there any policy around flexible work arrangements or disability support for someone in my situation
Expected: Vacation and Sick Leave.md
Improved Rank: nan

Retrieved:
  1. Working Remotely.md
  2. Other Protected Absences.md
  3. Working Remotely.md
  4. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 11
Query: Can I use a portion of my work hours during the week to study for a certification that is related to my role at Clef and if so is there a limit on how many hours I can dedicate to that
Expected: Continuing Education.md
Improved Rank: nan

Retrieved:
  1. Working Remotely.md
  2. Welcome to Clef.md
  3. Vacation and Sick Leave.md
  4. Other Protected Absences.md
  5. Working Remotely.md
----------------------------------------------------------------------------------------------------

Query ID: 21
Query: When I'm working from home I know I should be available on Slack but I'm unclear about the exact expectations — is there a specific set of hours where I need to be reachable for meetings and collaboration
Expected: Working Remotely.md
Improved Rank: 2.0

Retrieved:
  1. Communication and Transparency.md
  2. Working Remotely.md <-- EXPECTED
  3. Communication and Transparency.md
  4. Working Remotely.md <-- EXPECTED
  5. Communication and Transparency.md
----------------------------------------------------------------------------------------------------

Query ID: 37
Query: I need to schedule a meeting with a remote colleague but they are in a different time zone — what are the core hours during which all Clef employees are expected to be available for face to face meetings
Expected: Effective Meetings.md
Improved Rank: 2.0

Retrieved:
  1. Working Remotely.md
  2. Effective Meetings.md <-- EXPECTED
  3. Working Remotely.md
  4. Working Remotely.md
  5. Working Remotely.md
----------------------------------------------------------------------------------------------------

Create the failure-analysis framework

In [43]:
FAILURE_CATEGORIES = [
    "Ranking Failure",
    "Semantic Mismatch",
    "Vocabulary/Lexical Mismatch",
    "Cross-Document Confusion",
    "Chunking/Content Problem",
    "Low-Information Query",
    "Evaluation/Ground-Truth Issue",
    "Other"
]

print("Failure categories:")
for i, category in enumerate(FAILURE_CATEGORIES, 1):
    print(f"{i}. {category}")

Failure categories:
1. Ranking Failure
2. Semantic Mismatch
3. Vocabulary/Lexical Mismatch
4. Cross-Document Confusion
5. Chunking/Content Problem
6. Low-Information Query
7. Evaluation/Ground-Truth Issue
8. Other

Build the analysis dataframe

In [44]:
def prepare_failure_table(df, dataset):
    rows = []

    for _, row in df.iterrows():

        retrieved = row["retrieved_no_readme"]

        rows.append({
            "dataset": dataset,
            "query_id": row["query_id"],
            "query": row["query"],
            "expected_document": row["expected_document"],
            "improved_rank": row["improved_rank"],
            "rank_1_document": retrieved[0] if len(retrieved) > 0 else None,
            "rank_2_document": retrieved[1] if len(retrieved) > 1 else None,
            "rank_3_document": retrieved[2] if len(retrieved) > 2 else None,
            "rank_4_document": retrieved[3] if len(retrieved) > 3 else None,
            "rank_5_document": retrieved[4] if len(retrieved) > 4 else None,
            "failure_category": "",
            "reason": "",
            "recommended_action": "",
        })

    return pd.DataFrame(rows)


failure_analysis = pd.concat([
    prepare_failure_table(short_failures, "short"),
    prepare_failure_table(long_failures, "long")
], ignore_index=True)

print("Total remaining failures:", len(failure_analysis))

display(failure_analysis)

Total remaining failures: 31

,dataset,query_id,query,expected_document,improved_rank,rank_1_document,rank_2_document,rank_3_document,rank_4_document,rank_5_document,failure_category,reason,recommended_action
0,short,6,Is Thanksgiving a day off at Clef?,Holiday List.md,NaN,Vacation and Sick Leave.md,Other Protected Absences.md,Drug and Alcohol Policy.md,Welcome to Clef.md,Working Remotely.md,,,
1,short,10,"I need some time away, what are my options?",Vacation and Sick Leave.md,NaN,Communication and Transparency.md,Working Remotely.md,Other Protected Absences.md,Working Remotely.md,None,,,
2,short,15,"I've been here 5 years, what's the deal with t...",Sabbatical.md,2.0,Vacation and Sick Leave.md,Sabbatical.md,Welcome to Clef.md,Other Protected Absences.md,None,,,
3,short,18,Does Clef pay for online courses and books?,Continuing Education.md,2.0,Working Remotely.md,Continuing Education.md,Other Protected Absences.md,Continuing Education.md,Welcome to Clef.md,,,
4,short,36,How much do the founders make?,Salary and Equity Compensation.md,3.0,Budgeting.md,Complaint Policy.md,Salary and Equity Compensation.md,Salary and Equity Compensation.md,Objectives and Key Results.md,,,
5,short,46,"I have a family emergency, what should I do?",Other Protected Absences.md,2.0,Working Remotely.md,Other Protected Absences.md,Working Remotely.md,Communication and Transparency.md,Communication and Transparency.md,,,
6,short,70,Can we have beer at a company celebration?,Drug and Alcohol Policy.md,2.0,Welcome to Clef.md,Drug and Alcohol Policy.md,Working Remotely.md,Continuing Education.md,Policy Changes.md,,,
7,short,71,Can Clef fire me without a reason?,At-Will Employment.md,NaN,Complaint Policy.md,Employee Privacy.md,Employee Privacy.md,Other Protected Absences.md,Employee Privacy.md,,,
8,short,76,What are Clef's core values?,Clef Values.md,NaN,Welcome to Clef.md,Continuing Education.md,Equal Opportunity Employment.md,None,None,,,
9,short,78,How does Clef think about inclusion?,Clef Values.md,NaN,Equal Opportunity Employment.md,Welcome to Clef.md,Welcome to Clef.md,Welcome to Clef.md,None,,,
10,short,79,Why does Clef emphasize trust?,Clef Values.md,NaN,Welcome to Clef.md,One on Ones.md,Employee Privacy.md,None,None,,,
11,short,80,What is Clef's mission?,Mission Statement.md,NaN,Welcome to Clef.md,Welcome to Clef.md,Handbook Introduction.md,None,None,,,
12,short,81,What problem is Clef trying to solve?,Mission Statement.md,NaN,Complaint Policy.md,Product Manifesto.md,Welcome to Clef.md,Welcome to Clef.md,None,,,
13,short,84,How does Clef celebrate a new employee's first...,Welcome to Clef.md,2.0,Referral Bonuses.md,Welcome to Clef.md,Welcome to Clef.md,Policy Changes.md,Continuing Education.md,,,
14,short,85,"I just got hired, where do I start?",Welcome to Clef.md,2.0,Referral Bonuses.md,Welcome to Clef.md,Working Remotely.md,Budgeting.md,None,,,
15,short,87,Who is the CEO of Clef?,Handbook Introduction.md,3.0,Welcome to Clef.md,Welcome to Clef.md,Handbook Introduction.md,None,None,,,
16,short,96,What happens on Fridays in terms of team updates?,Communication and Transparency.md,2.0,Policy Changes.md,Communication and Transparency.md,Communication and Transparency.md,Policy Changes.md,Communication and Transparency.md,,,
17,short,99,Who do employees report to at Clef?,Direct Reports.md,2.0,Complaint Policy.md,Direct Reports.md,Employee Privacy.md,Other Protected Absences.md,None,,,
18,short,100,What is Clef's core product value?,Product Manifesto.md,NaN,Welcome to Clef.md,Welcome to Clef.md,Equal Opportunity Employment.md,None,None,,,
19,short,102,How is company spending organized at Clef?,Budgeting.md,NaN,Continuing Education.md,Continuing Education.md,Welcome to Clef.md,Welcome to Clef.md,Working Remotely.md,,,
20,short,103,What are the budget categories at Clef?,Budgeting.md,NaN,Continuing Education.md,Continuing Education.md,Sharing Files.md,Working Remotely.md,None,,,
21,short,108,What are the meeting time requirements at Clef?,Effective Meetings.md,NaN,Welcome to Clef.md,One on Ones.md,Continuing Education.md,Welcome to Clef.md,Vacation and Sick Leave.md,,,
22,short,111,What tools does Clef use for policy discussions?,Policy Changes.md,NaN,Working Remotely.md,Welcome to Clef.md,None,None,None,,,
23,short,112,Why did Clef open source their employee handbook?,README.md,NaN,Handbook Introduction.md,Policy Changes.md,Sharing Files.md,Employee Privacy.md,Complaint Policy.md,,,
24,short,116,If something bad happens at work who should I ...,Complaint Policy.md,NaN,One on Ones.md,One on Ones.md,Effective Meetings.md,Working Remotely.md,Working Remotely.md,,,
25,short,117,Does the code of conduct apply inside the offi...,Code of Conduct in the Community.md,2.0,Employee Privacy.md,Code of Conduct in the Community.md,Employee Privacy.md,Working Remotely.md,None,,,
26,long,2,My spouse and I are expecting a baby in a few ...,New Parent Leave.md,2.0,Other Protected Absences.md,New Parent Leave.md,Healthcare and Disability Insurance.md,Working Remotely.md,None,,,
27,long,4,I have a chronic illness that sometimes makes ...,Vacation and Sick Leave.md,NaN,Working Remotely.md,Other Protected Absences.md,Working Remotely.md,Working Remotely.md,None,,,
28,long,11,Can I use a portion of my work hours during th...,Continuing Education.md,NaN,Working Remotely.md,Welcome to Clef.md,Vacation and Sick Leave.md,Other Protected Absences.md,Working Remotely.md,,,
29,long,21,When I'm working from home I know I should be ...,Working Remotely.md,2.0,Communication and Transparency.md,Working Remotely.md,Communication and Transparency.md,Working Remotely.md,Communication and Transparency.md,,,
30,long,37,I need to schedule a meeting with a remote col...,Effective Meetings.md,2.0,Working Remotely.md,Effective Meetings.md,Working Remotely.md,Working Remotely.md,Working Remotely.md,,,

Add automatic failure signals

In [22]:
def classify_signal(row):

    rank = row["improved_rank"]

    if rank is not None and rank > 1:
        return "Correct document retrieved below Top-1"

    if rank is None:
        return "Expected document absent from retrieved results"

    return "Unknown"


failure_analysis["automatic_signal"] = failure_analysis.apply(
    classify_signal,
    axis=1
)

display(
    failure_analysis[
        [
            "dataset",
            "query_id",
            "query",
            "expected_document",
            "improved_rank",
            "rank_1_document",
            "automatic_signal"
        ]
    ]
)

,dataset,query_id,query,expected_document,improved_rank,rank_1_document,automatic_signal
0,short,6,Is Thanksgiving a day off at Clef?,Holiday List.md,NaN,Vacation and Sick Leave.md,Unknown
1,short,10,"I need some time away, what are my options?",Vacation and Sick Leave.md,NaN,Communication and Transparency.md,Unknown
2,short,15,"I've been here 5 years, what's the deal with t...",Sabbatical.md,2.0,Vacation and Sick Leave.md,Correct document retrieved below Top-1
3,short,18,Does Clef pay for online courses and books?,Continuing Education.md,2.0,Working Remotely.md,Correct document retrieved below Top-1
4,short,36,How much do the founders make?,Salary and Equity Compensation.md,3.0,Budgeting.md,Correct document retrieved below Top-1
5,short,46,"I have a family emergency, what should I do?",Other Protected Absences.md,2.0,Working Remotely.md,Correct document retrieved below Top-1
6,short,70,Can we have beer at a company celebration?,Drug and Alcohol Policy.md,2.0,Welcome to Clef.md,Correct document retrieved below Top-1
7,short,71,Can Clef fire me without a reason?,At-Will Employment.md,NaN,Complaint Policy.md,Unknown
8,short,76,What are Clef's core values?,Clef Values.md,NaN,Welcome to Clef.md,Unknown
9,short,78,How does Clef think about inclusion?,Clef Values.md,NaN,Equal Opportunity Employment.md,Unknown
10,short,79,Why does Clef emphasize trust?,Clef Values.md,NaN,Welcome to Clef.md,Unknown
11,short,80,What is Clef's mission?,Mission Statement.md,NaN,Welcome to Clef.md,Unknown
12,short,81,What problem is Clef trying to solve?,Mission Statement.md,NaN,Complaint Policy.md,Unknown
13,short,84,How does Clef celebrate a new employee's first...,Welcome to Clef.md,2.0,Referral Bonuses.md,Correct document retrieved below Top-1
14,short,85,"I just got hired, where do I start?",Welcome to Clef.md,2.0,Referral Bonuses.md,Correct document retrieved below Top-1
15,short,87,Who is the CEO of Clef?,Handbook Introduction.md,3.0,Welcome to Clef.md,Correct document retrieved below Top-1
16,short,96,What happens on Fridays in terms of team updates?,Communication and Transparency.md,2.0,Policy Changes.md,Correct document retrieved below Top-1
17,short,99,Who do employees report to at Clef?,Direct Reports.md,2.0,Complaint Policy.md,Correct document retrieved below Top-1
18,short,100,What is Clef's core product value?,Product Manifesto.md,NaN,Welcome to Clef.md,Unknown
19,short,102,How is company spending organized at Clef?,Budgeting.md,NaN,Continuing Education.md,Unknown
20,short,103,What are the budget categories at Clef?,Budgeting.md,NaN,Continuing Education.md,Unknown
21,short,108,What are the meeting time requirements at Clef?,Effective Meetings.md,NaN,Welcome to Clef.md,Unknown
22,short,111,What tools does Clef use for policy discussions?,Policy Changes.md,NaN,Working Remotely.md,Unknown
23,short,112,Why did Clef open source their employee handbook?,README.md,NaN,Handbook Introduction.md,Unknown
24,short,116,If something bad happens at work who should I ...,Complaint Policy.md,NaN,One on Ones.md,Unknown
25,short,117,Does the code of conduct apply inside the offi...,Code of Conduct in the Community.md,2.0,Employee Privacy.md,Correct document retrieved below Top-1
26,long,2,My spouse and I are expecting a baby in a few ...,New Parent Leave.md,2.0,Other Protected Absences.md,Correct document retrieved below Top-1
27,long,4,I have a chronic illness that sometimes makes ...,Vacation and Sick Leave.md,NaN,Working Remotely.md,Unknown
28,long,11,Can I use a portion of my work hours during th...,Continuing Education.md,NaN,Working Remotely.md,Unknown
29,long,21,When I'm working from home I know I should be ...,Working Remotely.md,2.0,Communication and Transparency.md,Correct document retrieved below Top-1
30,long,37,I need to schedule a meeting with a remote col...,Effective Meetings.md,2.0,Working Remotely.md,Correct document retrieved below Top-1

Manually classify the failures

In [23]:
classification_options = {
    1: "Ranking Failure",
    2: "Semantic Mismatch",
    3: "Vocabulary/Lexical Mismatch",
    4: "Cross-Document Confusion",
    5: "Chunking/Content Problem",
    6: "Low-Information Query",
    7: "Evaluation/Ground-Truth Issue",
    8: "Other"
}

for i, category in classification_options.items():
    print(f"{i}. {category}")

1. Ranking Failure
2. Semantic Mismatch
3. Vocabulary/Lexical Mismatch
4. Cross-Document Confusion
5. Chunking/Content Problem
6. Low-Information Query
7. Evaluation/Ground-Truth Issue
8. Other

Save the failure analysis

In [24]:
failure_analysis.to_csv(
    "remaining_failure_analysis.csv",
    index=False,
    encoding="utf-8"
)

failure_analysis.to_json(
    "remaining_failure_analysis.json",
    orient="records",
    indent=2,
    force_ascii=False
)

print("Saved:")
print("  remaining_failure_analysis.csv")
print("  remaining_failure_analysis.json")

Saved:
  remaining_failure_analysis.csv
  remaining_failure_analysis.json

Generate category summary

In [ ]:
print("=" * 80)
print("FAILURE CATEGORY SUMMARY")
print("=" * 80)

summary = (
    failure_analysis[
        failure_analysis["failure_category"] != ""
    ]
    .groupby(["dataset", "failure_category"])
    .size()
    .reset_index(name="count")
    .sort_values(["dataset", "count"], ascending=[True, False])
)

display(summary)

Calculate percentages

In [ ]:
summary["percentage"] = (
    summary.groupby("dataset")["count"]
    .transform(lambda x: x / x.sum() * 100)
    .round(2)
)

display(summary)

Identify the dominant problem

In [ ]:
for dataset in ["short", "long"]:

    subset = summary[
        summary["dataset"] == dataset
    ]

    if len(subset) == 0:
        continue

    top = subset.iloc[0]

    print(
        f"{dataset.upper()}: "
        f"{top['failure_category']} "
        f"({top['count']} failures, "
        f"{top['percentage']}%)"
    )

Save final summary

In [ ]:
summary.to_csv(
    "failure_category_summary.csv",
    index=False,
    encoding="utf-8"
)

summary.to_json(
    "failure_category_summary.json",
    orient="records",
    indent=2,
    force_ascii=False
)

print("Final summary saved.")